# Generated by Django 6.0.6 on 2026-07-24 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('body', models.TextField(max_length=2000, verbose_name='本文')),
                ('Page_date', models.DateField(verbose_name='日付')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='myjob/piture/', verbose_name='画像')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='NONAME', max_length=255, verbose_name='名前')),
                ('message', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myjob.page')),
            ],
        ),
    ]
