# Generated by Django 6.0.6 on 2026-07-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target',
            new_name='page',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='NONAME', max_length=255, verbose_name='名前'),
        ),
    ]
